### ISSUE TITLE
Create login form in Admin panel

### ISSUE THREAD

**Issue by pavelkeyzik** [pavelkeyzik/just-for-fun#13]
# Task
We have an admin page `src/pages/Admin.js` (URL endpoint: `/admin`). You have to add here a login component with a form that has login and password inputs. Also, add the submit button, but instead of calling some API just write `event.preventDefault()` for submitting a form. Please, use components from the [Reactstrap library](https://reactstrap.github.io/) instead of writing your own.

# Before start

Read the [contribution guide](https://github.com/pavelkeyzik/just-for-fun/blob/master/CONTRIBUTING.md). If you find a mistake or any problem to run project please let me know about it.

# Helpful information:
1. Your changes will be in `src/pages/Admin.js` file.
2. Login component should be in `src/pages/admin/Login.js`
3. We use **reactstrap**. Documentation is [here](https://reactstrap.github.io/)

If you want to work on this issue please leave a comment below. Let's people know that this issue is already taken.

**Comment by arturoalviar** [comment]
Hey, is it alright if I take this one?

**Comment by pavelkeyzik** [comment]
@arturoalviar sure :blush:
