### ISSUE TITLE
Add 404 page for client version

### ISSUE THREAD

**Issue by pavelkeyzik** [pavelkeyzik/just-for-fun#17]
# Task
Add a 404 page with a button that opens the home page of our site.

**Page title**: 404 Page Not Found
**Text**: Sorry! We didn't find anything interesting for you here. Please, click the button below to go home.
**Button text**: Go to home page

# Before start

Read the [contribution guide](https://github.com/pavelkeyzik/just-for-fun/blob/master/CONTRIBUTING.md). If you find a mistake or any problem to run project please let me know about it.

# Helpful information:
1. Add route without a path to the `src/pages/Main.js` file.
2. Create `NotFound` component in `src/pages/main/NotFound.js`
3. We use **reactstrap**. Documentation is [here](https://reactstrap.github.io/)

If you want to work on this issue please leave a comment below. Let's people know that this issue is already taken.

**Comment by albertmolodec** [comment]
@pavelkeyzik 
Can I take this task?
I'll try to do it towards the end of the day.

**Comment by pavelkeyzik** [comment]
@albertmolodec Sure! I'll assign you 😊
