### ISSUE TITLE
Write simple unit tests for configuration file

### ISSUE THREAD

**Issue by pavelkeyzik** [pavelkeyzik/just-for-fun#19]
# Task
Open file `src/__tests__/config.test.js` and add tests here for all variables from `src/config.js` file.

# Before start

Read the [contribution guide](https://github.com/pavelkeyzik/just-for-fun/blob/master/CONTRIBUTING.md). If you find a mistake or any problem to run project please let me know about it.

# Helpful information:
1. Your changes will be in `src/__tests__/config.test.js` file.
2. In the test file, you have one test already. You can use it as an example to create other tests.
3. We use **jest** testing library. Documentation is [here](https://jestjs.io/docs/en/getting-started)

If you want to work on this issue please leave a comment below. Let's people know that this issue is already taken.

**Comment by fllprbt** [comment]
Can I grab it? Also except the initialisation tests, should we implement anything else?

**Comment by pavelkeyzik** [comment]
@fllprbt of course you can grab it. You need to check only initial state :blush:
