### ISSUE TITLE
Fix grid layout for list of places

### ISSUE THREAD

**Issue by pavelkeyzik** [pavelkeyzik/just-for-fun#5]
# The problem and task
We have a page with a list of places (`/places` endpoint)

In the mobile version, it looks great but on the big screen, I want to see grid instead of items with different width (See the example below)

![image](https://user-images.githubusercontent.com/17102399/66379058-6a1eb980-e9bd-11e9-9d45-aa07851aeff0.png)

On **big displays**, max count of items in a row **3**. Make sure that on all screen sizes the grid looks great.

# Before start

Read the [contribution guide](https://github.com/pavelkeyzik/just-for-fun/blob/master/CONTRIBUTING.md). If you find a mistake or any problem to run project please let me know about it.

# Helpful information:
1. Your changes will be in `src/pages/places/PlacesGrid.js` file.
2. We use **reactstrap**. Documentation is [here](https://reactstrap.github.io/)

If you want to work on this issue please leave a comment below. Let's people know that this issue is already taken.

**Comment by Sky0023** [comment]
Hi @pavelkeyzik  can I try to solve it?

**Comment by pavelkeyzik** [comment]
@Sky0023 of course. If you'll need help you can text me too.

**Comment by pavelkeyzik** [comment]
Maybe somebody wants to take this issue?

**Comment by Sky0023** [comment]
Okay

**Comment by MAYTESI** [comment]
Can I try to solve, too?

**Comment by pavelkeyzik** [comment]
@MAYTESI sure you can
