### ISSUE TITLE
Create page with list of contributors

### ISSUE THREAD

**Issue by pavelkeyzik** [pavelkeyzik/just-for-fun#9]
# Task
You should create a new page where we'll see contributors. It should be a table like this:

| # | Username | GitHub |
|--|:-:|:-:|
|1|pavelkeyzik|https://github.com/pavelkeyzik|
|2|...|...|

Don't worry about the good look on mobile screens now and don't forget about page title like on Places page (`/places`).

# Before start

Read the [contribution guide](https://github.com/pavelkeyzik/just-for-fun/blob/master/CONTRIBUTING.md). If you find a mistake or any problem to run project please let me know about it.

# Helpful information:
1. Create a new file `src/pages/Contributors.js`
2. For styles create a file `src/pages/Contributors.css`
3. An endpoint name should be `/contributors`
4. We use **reactstrap**. Documentation is [here](https://reactstrap.github.io/)

If you want to work on this issue please leave a comment below. Let's people know that this issue is already taken.

**Comment by Eagle732** [comment]
Hii, I want to work on this issue. Can I proceed??

**Comment by pavelkeyzik** [comment]
@Eagle732 sure 😊
